import { Header } from '@/components/shared'
import './globals.css'
import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'

const kanit = Kanit({
  subsets: ['latin'],
  weight:["200","300","400","500","600","700"]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
		<html lang="en">
			<body className={`${kanit.className} dark`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
